### Get packaging and delivery charge for accessory
GET localhost:8082/packaging-and-delivery/api/packaging-and-delivery-charge?componentType=integral-item&count=2
Content-Type: application/json

### Get packaging and delivery charge for unknown
GET localhost:8082/packaging-and-delivery/api/packaging-and-delivery-charge?componentType=unknown&count=2
Content-Type: application/json