### Get packaging and delivery charge for accessory
GET http://localhost:8082/packaging-and-delivery/api/packaging-and-delivery-charge?componentType=integral-item&count=2
Content-Type: application/json

### Get packaging and delivery charge for unknown
GET http://localhost:8082/packaging-and-delivery/api/packaging-and-delivery-charge?componentType=unknown&count=2
Content-Type: application/json

### Get packaging and delivery charge with blank component type
GET http://localhost:8082/packaging-and-delivery/api/packaging-and-delivery-charge?componentType=&count=2
Content-Type: application/json

### Get packaging and delivery charge for accessory with negative count
GET http://localhost:8082/packaging-and-delivery/api/packaging-and-delivery-charge?componentType=accessory&count=-2
Content-Type: application/json

### Get packaging and delivery charge with blank component type and negative count
GET http://localhost:8082/packaging-and-delivery/api/packaging-and-delivery-charge?componentType=&count=-2
Content-Type: application/json
