server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server
  cloud:
    service-registry:
      auto-registration:
        enabled: false

logging:
  file:
    name: /var/logs/service-registry.log
    path: /var/logs
  level:
    org.springframework.web: "debug"

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles:
    active: dev