server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    service-registry:
      auto-registration:
        enabled: false

logging:
  file:
    name: logs/service-registry.log
    path: logs
  level:
    org.springframework.web: "debug"

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false