server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

logging:
  file:
    name: authorization/logs/authorization.log
    path: authorization/logs

spring:
  application:
    name: authorization
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      platform: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:return_order_management;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: ${DB_USERNAME:ritam}
    password: ${DB_PASSWORD:password}
    embedded-database-connection: h2
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

authorization:
  jwt:
    secret-key: ${SECRET_KEY:secret}

---

spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://service-registry-ritam.herokuapp.com/eureka

---

spring:
  profiles:
    active: dev