### Login test with correct credential
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=ritam@gmail.com&password=password


### Login test with wrong usernme
POST http://localhost:8181/login
Content-Type: application/x-www-form-urlencoded

username=pritam@gmail.com&password=password


### Login test with incorrect request
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

email=ritam@gmail.com&password=password

### Login test with incorrect username
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=pritam@gmail.com&password=password


### Login test with wrong credential
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=ritam@gmail.com&password=blah


### Get Customer with empty token
GET http://localhost:8080/authenticate
Accept: application/json


### Get Customer with valid token
GET http://localhost:8080/authenticate
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyaXRhbUBnbWFpbC5jb20iLCJleHAiOjI5NzEyODQzNjM5NjMwMDB9.p7m5gaEljNkTWs7YB6Ys4BUcFtEW3qFGIl3eHkVGIQXLSgD96VXoLLKNsMrFWO5nobgpbYWs0iDrwKtDWqn3Cw


### Get Customer with invalid token
GET http://localhost:8080/authenticate
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyaXRhbUBnbWFpbC5jb20iLCJleHAiOjI5NzEyODQzNjM5NjMwMDB9.p7m5gaEljNkTWs7YB6Ys4BUcFtEW3qFGIl3eHkVGIQXLSgD96WXoLLKNsMrFWO5nobgpbYWs0iDrwKtDWqn3Cz


### Create new customer
POST http://localhost:8080/signup
Accept: application/json
Content-Type: application/json

{
  "email": "shuktika.mahanty@gmail.com",
  "password": "Password@123",
  "firstName": "Shuktika",
  "lastName": "Mahanty",
  "contactNumber": "7086653484"
}

### Login with new user
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=shuktika.mahanty@gmail.com&password=Password@123


### Get Customer with valid token of new user
GET http://localhost:8080/authenticate
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzaHVrdGlrYS5tYWhhbnR5QGdtYWlsLmNvbSIsImV4cCI6Mjk3MTMyMDAyNTkxNDAwMH0.QhMU_aTk3ibBqs6uqNWqbPL07KIxuzztjwomuR33VytsOPxA0yoFpSCgd_73lst1DuQho6kJuT6FtippJpURFw


