server:
  port: ${PORT:8081}
  error:
    include-message: always
    include-binding-errors: always

logging:
  file:
    name: /var/logs/component-processing.log
    path: /var/logs

spring:
  application:
    name: component-processing
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:return_order_management;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: ${DB_USERNAME:ritam}
    password: ${DB_PASSWORD:password}
    embedded-database-connection: h2
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: "*"

component-processing:
  integral-item:
    processing-duration: 5
    processing-charge: 500
  accessory:
    processing-duration: 2
    processing-charge: 300

---

spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  profiles:
    active: dev