server:
  port: 8081

spring:
  application:
    name: component_processing

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

component-processing:
  integral-item:
    processing-duration: 5
    processing-charge: 500
  accessory:
    processing-duration: 2
    processing-charge: 300

client:
  value: packaging-and-delivery
  url: http://localhost:8082