version: "3.3"

services:
  service-registry:
    image: ritamchakraborty/return_order_service_registry:1.0
    ports:
      - 8761:8761
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 60s
      retries: 5
      timeout: 10s
  config-server:
    image: ritamchakraborty/return_order_config_server:1.0
    environment:
      SERVICE_REGISTRY_URL: http://service-registry:8761/eureka
    ports:
      - 8286:8286
    depends_on:
      - service-registry
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8286/actuator/health" ]
      interval: 60s
      retries: 5
      timeout: 10s
  authorization:
    image: ritamchakraborty/return_order_authorization:1.0
    environment:
      CONFIG_SERVER_URL: http://config-server:8286
      DB_USERNAME: ritam
      DB_PASSWORD: password
      SECRET_KEY: secret
    ports:
      - 8080:8080
    depends_on:
      - config-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 60s
      retries: 5
      timeout: 10s
  packaging-and-delivery:
    image: ritamchakraborty/return_order_packaging_and_delivery:1.0
    environment:
      CONFIG_SERVER_URL: http://config-server:8286
    ports:
      - 8082:8082
    depends_on:
      - config-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 60s
      retries: 5
      timeout: 10s
  component-processing:
    image: ritamchakraborty/return_order_component_processing:1.0
    environment:
      CONFIG_SERVER_URL: http://config-server:8286
      DB_USERNAME: ritam
      DB_PASSWORD: password
      PACKAGING_AND_DELIVERY_API_URL: http://packaging-and-delivery:8082
    ports:
      - 8081:8081
    depends_on:
      - config-server
      - packaging-and-delivery
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 60s
      retries: 5
      timeout: 10s
  api-gateway:
    image: ritamchakraborty/return_order_api_gateway:1.0
    environment:
      CONFIG_SERVER_URL: http://config-server:8286
    ports:
      - 8181:8181
    depends_on:
      - config-server
      - authorization
      - component-processing