version: "2.1"

services:
  service-registry:
    image: ritamchakraborty/return_order_service_registry:1.0
    ports:
      - 8761:8761
    restart: on-failure
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
  authorization:
    image: ritamchakraborty/return_order_authorization:1.0
    environment:
      PROFILE: docker
      DB_USERNAME: ritam
      DB_PASSWORD: password
      SECRET_KEY: secret
    ports:
      - 8080:8080
    depends_on:
      service-registry:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
  packaging-and-delivery:
    image: ritamchakraborty/return_order_packaging_and_delivery:1.0
    environment:
      PROFILE: docker
    ports:
      - 8082:8082
    depends_on:
      service-registry:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
  component-processing:
    image: ritamchakraborty/return_order_component_processing:1.0
    environment:
      PROFILE: docker
      DB_USERNAME: ritam
      DB_PASSWORD: password
    ports:
      - 8081:8081
    depends_on:
      service-registry:
        condition: service_healthy
      packaging-and-delivery:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
  api-gateway:
    image: ritamchakraborty/return_order_api_gateway:1.0
    environment:
      PROFILE: docker
    ports:
      - 8181:8181
    depends_on:
      service-registry:
        condition: service_healthy
      authorization:
        condition: service_healthy
      component-processing:
        condition: service_healthy
    restart: on-failure