server:
  port: ${PORT:8181}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authrization
          uri: https://authorization-ritam.herokuapp.com
          predicates:
            - Path=/authorization/**
        - id: component-processing
          uri: https://component-processing-ritam.herokuapp.com
          predicates:
            - Path=/component-processing/**
          filters:
            - AuthenticationFilter