server:
  port: ${PORT:8181}

spring:
  application:
    name: api-gateway
  mvc:
    async:
      request-timeout: 5000
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST

logging:
  file:
    name: /var/logs/api-gateway.log
    path: /var/logs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    prefer-ip-address: true

---

spring:
  profiles:
    active: ${PROFILE:dev}