server:
  port: ${PORT:8181}

spring:
  application:
    name: api-gateway
  mvc:
    async:
      request-timeout: 5000
  cloud:
    gateway:
      routes:
        - id: authrization
          uri: https://authorization-ritam.herokuapp.com
          predicates:
            - Path=/authorization/**
        - id: component-processing
          uri: https://component-processing-ritam.herokuapp.com
          predicates:
            - Path=/component-processing/**
          filters:
            - name: AuthenticationFilter
              args:
                authenticationUrl: https://authorization-ritam.herokuapp.com
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST

logging:
  file:
    name: /var/logs/api-gateway.log
    path: /var/logs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true