server:
  port: 8082

spring:
  application:
    name: packaging-and-delivery

logging:
  file:
    name: logs/packaging-and-delivery.log
    path: logs
  level:
    org.springframework.web: "debug"

packaging-and-delivery-cost:
  packaging-items:
    integral-item: 100
    accessory: 50
    protective-sheath: 50

  delivery-items:
    integral-item: 200
    accessory: 100