server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: packaging_and_delivery

packaging-and-delivery-cost:
  packaging-items:
    integral-item: 100
    accessory: 50
    protective-sheath: 50

  delivery-items:
    integral-item: 200
    accessory: 100