server:
  port: 8082

spring:
  application:
    name: packaging-and-delivery
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  file:
    name: packaging_and_delivery/logs/packaging-and-delivery.log
    path: packaging_and_delivery/logs
  level:
    org.springframework.web: "debug"

management:
  endpoints:
    web:
      exposure:
        include: "*"

packaging-and-delivery-cost:
  packaging-items:
    integral-item: 100
    accessory: 50
    protective-sheath: 50

  delivery-items:
    integral-item: 200
    accessory: 100