server:
  port: ${PORT:8082}

spring:
  application:
    name: packaging-and-delivery
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  file:
    name: /var/logs/packaging-and-delivery.log
    path: /var/logs

management:
  endpoints:
    web:
      exposure:
        include: "*"

packaging-and-delivery-cost:
  packaging-items:
    integral-item: 100
    accessory: 50
    protective-sheath: 50

  delivery-items:
    integral-item: 200
    accessory: 100

---

spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

---

spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    prefer-ip-address: true

---

spring:
  profiles:
    active: ${PROFILE:dev}