### Get process defail
GET http://localhost:8181/component-processing/api/process-detail
Content-Type: application/json
Accept: application/json

{
  "name": "Miss Mahanty",
  "contactNumber": "7980546384",
  "componentType": "integral-item",
  "componentName": "lipstick",
  "quantity": 5
}

### Get process defail for worong component type
GET http://localhost:8181/component-processing/api/process-detail
Content-Type: application/json
Accept: application/json

{
  "name": "Miss Mahanty",
  "contactNumber": "7980546384",
  "componentType": "unknown",
  "componentName": "lipstick",
  "quantity": 5
}