server:
  port: 8286

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/ritam6/config-server.git
          clone-on-start: true

logging:
  file:
    name: config_server/logs/config-server.log
    path: config_server/logs
  level:
    org.springframework.web: "debug"

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL}
  instance:
    hostname: localhost