server:
  port: 8286

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RitamChakraborty/config-server
          clone-on-start: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    hostname: localhost